
#ifndef __PIN_MAP_H__
#define __PIN_MAP_H__


#if !defined(BOARD_PROD) && !defined(BOARD_LAUNCH_S) && !defined(BOARD_LAUNCH_SF)
#error "Board not defined"
#endif


/* GPIO */
#define BOARD_GPIO_LED_STATUS_PIN (GPIOCC32XX_GPIO_11)
#define BOARD_GPIO_LED_ERROR_PIN (GPIOCC32XX_GPIO_10)
#define BOARD_GPIO_LED_CONNECTION_PIN (GPIOCC32XX_GPIO_09)

#ifdef BOARD_PROD
#define BOARD_GPIO_BUTTON_PATIENT_PIN (GPIOCC32XX_GPIO_04)
#else
#define BOARD_GPIO_BUTTON_PATIENT_PIN (GPIOCC32XX_GPIO_22)
#endif

#ifdef BOARD_PROD
#define BOARD_GPIO_BUTTON_RESET_PIN (GPIOCC32XX_GPIO_03)
#else
#define BOARD_GPIO_BUTTON_RESET_PIN (GPIOCC32XX_GPIO_13)
#endif

#define BOARD_GPIO_SENSOR_PIN (GPIOCC32XX_GPIO_02)


/* Buzzer */
#ifdef BOARD_PROD
#define BOARD_BUZZER_PIN (GPIOCC32XX_GPIO_05)
#else
#define BOARD_BUZZER_PIN (GPIOCC32XX_GPIO_00)
#endif


/* Shutter */
#ifdef BOARD_PROD
#define BOARD_SHUTTER_EN_PIN (GPIOCC32XX_GPIO_27)
#else
#define BOARD_SHUTTER_EN_PIN (GPIOCC32XX_GPIO_30)
#endif

#define BOARD_SHUTTER_COIL0_P_PIN (GPIOCC32XX_GPIO_08)
#define BOARD_SHUTTER_COIL0_N_PIN (GPIOCC32XX_GPIO_17)

#ifdef BOARD_PROD
#define BOARD_SHUTTER_COIL1_P_PIN (GPIOCC32XX_GPIO_07)
#else
#define BOARD_SHUTTER_COIL1_P_PIN (GPIOCC32XX_GPIO_01)
#endif

#define BOARD_SHUTTER_COIL1_N_PIN (GPIOCC32XX_GPIO_16)


/* Drum */
#ifdef BOARD_PROD
#define BOARD_DRUM_EN_PIN (GPIOCC32XX_GPIO_26)
#else
#define BOARD_DRUM_EN_PIN (GPIOCC32XX_GPIO_12)
#endif

#define BOARD_DRUM_COIL0_P_PIN (GPIOCC32XX_GPIO_14)

#ifdef BOARD_PROD
#define BOARD_DRUM_COIL0_N_PIN (GPIOCC32XX_GPIO_22)
#else
#define BOARD_DRUM_COIL0_N_PIN (GPIOCC32XX_GPIO_01)
#endif

#define BOARD_DRUM_COIL1_P_PIN (GPIOCC32XX_GPIO_15)
#define BOARD_DRUM_COIL1_N_PIN (GPIOCC32XX_GPIO_28)


#endif
