
#ifndef __PIN_MAP_H__
#define __PIN_MAP_H__


#if !defined(BOARD_PROD) && !defined(BOARD_LAUNCH_S) && !defined(BOARD_LAUNCH_SF)
#error "Board not defined"
#endif


/* GPIO */
#ifdef BOARD_PROD
#define BOARD_GPIO_LED_STATUS_PIN (GPIOCC32XX_GPIO_11)
#define BOARD_GPIO_LED_ERROR_PIN (GPIOCC32XX_GPIO_10)
#define BOARD_GPIO_LED_CONNECTION_PIN (GPIOCC32XX_GPIO_09)

#define BOARD_GPIO_BUTTON_PATIENT_PIN (GPIOCC32XX_GPIO_12)
#define BOARD_GPIO_BUTTON_RESET_PIN (GPIOCC32XX_GPIO_03)

#define BOARD_SENSOR_PIN (GPIOCC32XX_GPIO_04)
#define BOARD_SENSOR_ADC_PIN (ADCCC32XX_PIN_59_CH_2)
#else
#define BOARD_GPIO_LED_STATUS_PIN (GPIOCC32XX_GPIO_11)
#define BOARD_GPIO_LED_ERROR_PIN (GPIOCC32XX_GPIO_10)
#define BOARD_GPIO_LED_CONNECTION_PIN (GPIOCC32XX_GPIO_09)

#define BOARD_GPIO_BUTTON_PATIENT_PIN (GPIOCC32XX_GPIO_13)
#define BOARD_GPIO_BUTTON_RESET_PIN (GPIOCC32XX_GPIO_03)

#define BOARD_SENSOR_PIN (GPIOCC32XX_GPIO_03)
#define BOARD_SENSOR_ADC_PIN (ADCCC32XX_PIN_58_CH_1)
#endif


/* Buzzer */
#define BOARD_BUZZER_PIN (GPIOCC32XX_GPIO_05)


/* Shutter */
//#ifdef BOARD_PROD
#define BOARD_SHUTTER_EN_PIN (GPIOCC32XX_GPIO_27)
#define BOARD_SHUTTER_COIL0_P_PIN (GPIOCC32XX_GPIO_08)
#define BOARD_SHUTTER_COIL0_N_PIN (GPIOCC32XX_GPIO_17)
#define BOARD_SHUTTER_COIL1_P_PIN (GPIOCC32XX_GPIO_07)
#define BOARD_SHUTTER_COIL1_N_PIN (GPIOCC32XX_GPIO_16)
//#else
//#define BOARD_SHUTTER_EN_PIN (GPIOCC32XX_GPIO_30)
//#define BOARD_SHUTTER_COIL0_P_PIN (GPIOCC32XX_GPIO_08)
//#define BOARD_SHUTTER_COIL0_N_PIN (GPIOCC32XX_GPIO_17)
//#define BOARD_SHUTTER_COIL1_P_PIN (GPIOCC32XX_GPIO_14)
//#define BOARD_SHUTTER_COIL1_N_PIN (GPIOCC32XX_GPIO_16)
//#endif


/* Drum */
#ifdef BOARD_PROD
#define BOARD_DRUM_EN_PIN (GPIOCC32XX_GPIO_26)
#define BOARD_DRUM_COIL0_P_PIN (GPIOCC32XX_GPIO_01)
#define BOARD_DRUM_COIL0_N_PIN (GPIOCC32XX_GPIO_22)
#define BOARD_DRUM_COIL1_P_PIN (GPIOCC32XX_GPIO_15)
#define BOARD_DRUM_COIL1_N_PIN (GPIOCC32XX_GPIO_28)
#else
#define BOARD_DRUM_EN_PIN (GPIOCC32XX_GPIO_30)
#define BOARD_DRUM_COIL0_P_PIN (GPIOCC32XX_GPIO_08)
#define BOARD_DRUM_COIL0_N_PIN (GPIOCC32XX_GPIO_17)
#define BOARD_DRUM_COIL1_P_PIN (GPIOCC32XX_GPIO_14)
#define BOARD_DRUM_COIL1_N_PIN (GPIOCC32XX_GPIO_16)
#endif


#endif
