
#ifndef __PIN_MAP_H__
#define __PIN_MAP_H__


#if !defined(BOARD_PROD) && !defined(BOARD_LAUNCH_S) && !defined(BOARD_LAUNCH_SF)
#error "Board not defined"
#endif


/* GPIO */
#ifdef BOARD_PROD
#define BOARD_GPIO_LED_STATUS_PIN (GPIOCC32XX_GPIO_10)
#define BOARD_GPIO_LED_ERROR_PIN (GPIOCC32XX_GPIO_11)
#define BOARD_GPIO_LED_CONNECTION_PIN (GPIOCC32XX_GPIO_30)

#define BOARD_GPIO_BUTTON_PATIENT_PIN (GPIOCC32XX_GPIO_15)
#define BOARD_GPIO_BUTTON_RESET_PIN (GPIOCC32XX_GPIO_14)

#define BOARD_SENSOR_HIGH_PIN (GPIOCC32XX_GPIO_04)
#define BOARD_SENSOR_HIGH_ADC_PIN (ADCCC32XX_PIN_59_CH_2)

#define BOARD_SENSOR_LOW_PIN (GPIOCC32XX_GPIO_03)
#define BOARD_SENSOR_LOW_ADC_PIN (ADCCC32XX_PIN_58_CH_1)
#else
#define BOARD_GPIO_LED_STATUS_PIN (GPIOCC32XX_GPIO_11)
#define BOARD_GPIO_LED_ERROR_PIN (GPIOCC32XX_GPIO_10)
#define BOARD_GPIO_LED_CONNECTION_PIN (GPIOCC32XX_GPIO_09)

#define BOARD_GPIO_BUTTON_PATIENT_PIN (GPIOCC32XX_GPIO_13)
#define BOARD_GPIO_BUTTON_RESET_PIN (GPIOCC32XX_GPIO_03)

#define BOARD_SENSOR_HIGH_PIN (GPIOCC32XX_GPIO_03)
#define BOARD_SENSOR_HIGH_ADC_PIN (ADCCC32XX_PIN_58_CH_1)

#define BOARD_SENSOR_LOW_PIN (GPIOCC32XX_GPIO_04)
#define BOARD_SENSOR_LOW_ADC_PIN (ADCCC32XX_PIN_59_CH_2)
#endif


/* Buzzer */
#ifdef BOARD_PROD
#define BOARD_BUZZER_PIN (GPIOCC32XX_GPIO_09)
#define BOARD_BUZZER_PWM_PIN (PWMTimerCC32XX_PIN_64)
#else
#define BOARD_BUZZER_PIN (GPIOCC32XX_GPIO_05)
#endif


/* Shutter */
#define BOARD_SHUTTER_EN_PIN (GPIOCC32XX_GPIO_22)
#define BOARD_SHUTTER_SLEEP_PIN (GPIOCC32XX_GPIO_12)
#define BOARD_SHUTTER_RESET_PIN (GPIOCC32XX_GPIO_13)
#define BOARD_SHUTTER_DIR_PIN (GPIOCC32XX_GPIO_16)
#define BOARD_SHUTTER_STEP_PIN (GPIOCC32XX_GPIO_17)


/* Drum */
#define BOARD_DRUM_EN_PIN (GPIOCC32XX_GPIO_00)
#define BOARD_DRUM_SLEEP_PIN (GPIOCC32XX_GPIO_07)
#define BOARD_DRUM_RESET_PIN (GPIOCC32XX_GPIO_08)
#define BOARD_DRUM_DIR_PIN (GPIOCC32XX_GPIO_05)
#define BOARD_DRUM_STEP_PIN (GPIOCC32XX_GPIO_06)


#endif
